<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (dataset*)>
  <!ELEMENT dataset (postalcode?,avglivingarea?,avgland?,avgbedrooms?,avgrentalprice?,avgsalesprice?,count?)+>
  <!ELEMENT postalcode (#PCDATA)>
  <!ELEMENT avglivingarea (#PCDATA)>
  <!ELEMENT avgland (#PCDATA)>
  <!ELEMENT avgbedrooms (#PCDATA)>
  <!ELEMENT avgrentalprice (#PCDATA)>
  <!ELEMENT avgsalesprice (#PCDATA)>
  <!ELEMENT count (#PCDATA)>
]>
<main>
  <dataset>
    <postalcode>1083</postalcode>
    <avglivingarea>435</avglivingarea>
    <avgland>231</avgland>
    <avgbedrooms>2.7</avgbedrooms>
    <avgrentalprice>956</avgrentalprice>
    <avgsalesprice>254159</avgsalesprice>
    <count>210</count>
  </dataset>
  <dataset>
    <postalcode>1140</postalcode>
    <avglivingarea>145</avglivingarea>
    <avgland>200</avgland>
    <avgbedrooms>2.6</avgbedrooms>
    <avgrentalprice>1182</avgrentalprice>
    <avgsalesprice>282083</avgsalesprice>
    <count>400</count>
  </dataset>
  <dataset>
    <postalcode>1160</postalcode>
    <avglivingarea>153</avglivingarea>
    <avgland>363</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>1528</avgrentalprice>
    <avgsalesprice>506373</avgsalesprice>
    <count>504</count>
  </dataset>
  <dataset>
    <postalcode>1780</postalcode>
    <avglivingarea>175</avglivingarea>
    <avgland>1017</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>1102</avgrentalprice>
    <avgsalesprice>490417</avgsalesprice>
    <count>210</count>
  </dataset>
  <dataset>
    <postalcode>1970</postalcode>
    <avglivingarea>207</avglivingarea>
    <avgland>1067</avgland>
    <avgbedrooms>3.7</avgbedrooms>
    <avgrentalprice>2083</avgrentalprice>
    <avgsalesprice>642856</avgsalesprice>
    <count>231</count>
  </dataset>
  <dataset>
    <postalcode>2000</postalcode>
    <avglivingarea>141</avglivingarea>
    <avgland>92</avgland>
    <avgbedrooms>2.4</avgbedrooms>
    <avgrentalprice>1180</avgrentalprice>
    <avgsalesprice>356500</avgsalesprice>
    <count>23</count>
  </dataset>
  <dataset>
    <postalcode>2660</postalcode>
    <avglivingarea>141</avglivingarea>
    <avgland>227</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice>750</avgrentalprice>
    <avgsalesprice>234582</avgsalesprice>
    <count>30</count>
  </dataset>
  <dataset>
    <postalcode>1000</postalcode>
    <avglivingarea>211</avglivingarea>
    <avgland>230</avgland>
    <avgbedrooms>3.2</avgbedrooms>
    <avgrentalprice>2282</avgrentalprice>
    <avgsalesprice>878420</avgsalesprice>
    <count>218</count>
  </dataset>
  <dataset>
    <postalcode>1070</postalcode>
    <avglivingarea>334</avglivingarea>
    <avgland>348</avgland>
    <avgbedrooms>3.3</avgbedrooms>
    <avgrentalprice>799</avgrentalprice>
    <avgsalesprice>327067</avgsalesprice>
    <count>598</count>
  </dataset>
  <dataset>
    <postalcode>1081</postalcode>
    <avglivingarea>134</avglivingarea>
    <avgland>196</avgland>
    <avgbedrooms>2.6</avgbedrooms>
    <avgrentalprice>904</avgrentalprice>
    <avgsalesprice>246884</avgsalesprice>
    <count>197</count>
  </dataset>
  <dataset>
    <postalcode>1210</postalcode>
    <avglivingarea>167</avglivingarea>
    <avgland>195</avgland>
    <avgbedrooms>3.2</avgbedrooms>
    <avgrentalprice>1088</avgrentalprice>
    <avgsalesprice>409055</avgsalesprice>
    <count>162</count>
  </dataset>
  <dataset>
    <postalcode>1930</postalcode>
    <avglivingarea>145</avglivingarea>
    <avgland>481</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice>1097</avgrentalprice>
    <avgsalesprice>312309</avgsalesprice>
    <count>174</count>
  </dataset>
  <dataset>
    <postalcode>3090</postalcode>
    <avglivingarea>233</avglivingarea>
    <avgland>1628</avgland>
    <avgbedrooms>3.8</avgbedrooms>
    <avgrentalprice>1848</avgrentalprice>
    <avgsalesprice>518489</avgsalesprice>
    <count>352</count>
  </dataset>
  <dataset>
    <postalcode>1180</postalcode>
    <avglivingarea>226</avglivingarea>
    <avgland>1251</avgland>
    <avgbedrooms>3.5</avgbedrooms>
    <avgrentalprice>2277</avgrentalprice>
    <avgsalesprice>1000866</avgsalesprice>
    <count>1535</count>
  </dataset>
  <dataset>
    <postalcode>1190</postalcode>
    <avglivingarea>173</avglivingarea>
    <avgland>339</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>1393</avgrentalprice>
    <avgsalesprice>450597</avgsalesprice>
    <count>593</count>
  </dataset>
  <dataset>
    <postalcode>1200</postalcode>
    <avglivingarea>145</avglivingarea>
    <avgland>305</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>1530</avgrentalprice>
    <avgsalesprice>451416</avgsalesprice>
    <count>812</count>
  </dataset>
  <dataset>
    <postalcode>3300</postalcode>
    <avglivingarea>163</avglivingarea>
    <avgland>662</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>712</avgrentalprice>
    <avgsalesprice>247495</avgsalesprice>
    <count>27</count>
  </dataset>
  <dataset>
    <postalcode>1020</postalcode>
    <avglivingarea>148</avglivingarea>
    <avgland>346</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>989</avgrentalprice>
    <avgsalesprice>285104</avgsalesprice>
    <count>417</count>
  </dataset>
  <dataset>
    <postalcode>1080</postalcode>
    <avglivingarea>145</avglivingarea>
    <avgland>218</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>906</avgrentalprice>
    <avgsalesprice>258050</avgsalesprice>
    <count>618</count>
  </dataset>
  <dataset>
    <postalcode>1853</postalcode>
    <avglivingarea>133</avglivingarea>
    <avgland>314</avgland>
    <avgbedrooms>2.7</avgbedrooms>
    <avgrentalprice>820</avgrentalprice>
    <avgsalesprice>282556</avgsalesprice>
    <count>139</count>
  </dataset>
  <dataset>
    <postalcode>1932</postalcode>
    <avglivingarea>132</avglivingarea>
    <avgland>445</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice>1094</avgrentalprice>
    <avgsalesprice>327731</avgsalesprice>
    <count>85</count>
  </dataset>
  <dataset>
    <postalcode>2830</postalcode>
    <avglivingarea>142</avglivingarea>
    <avgland>363</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice></avgrentalprice>
    <avgsalesprice>274515</avgsalesprice>
    <count>29</count>
  </dataset>
  <dataset>
    <postalcode>3080</postalcode>
    <avglivingarea>243</avglivingarea>
    <avgland>1945</avgland>
    <avgbedrooms>4.1</avgbedrooms>
    <avgrentalprice>2288</avgrentalprice>
    <avgsalesprice>731080</avgsalesprice>
    <count>422</count>
  </dataset>
  <dataset>
    <postalcode>1030</postalcode>
    <avglivingarea>231</avglivingarea>
    <avgland>200</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>1214</avgrentalprice>
    <avgsalesprice>361158</avgsalesprice>
    <count>975</count>
  </dataset>
  <dataset>
    <postalcode>1040</postalcode>
    <avglivingarea>160</avglivingarea>
    <avgland>201</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>1644</avgrentalprice>
    <avgsalesprice>519878</avgsalesprice>
    <count>701</count>
  </dataset>
  <dataset>
    <postalcode>1060</postalcode>
    <avglivingarea>174</avglivingarea>
    <avgland>250</avgland>
    <avgbedrooms>3.1</avgbedrooms>
    <avgrentalprice>1513</avgrentalprice>
    <avgsalesprice>473664</avgsalesprice>
    <count>457</count>
  </dataset>
  <dataset>
    <postalcode>1130</postalcode>
    <avglivingarea>169</avglivingarea>
    <avgland>327</avgland>
    <avgbedrooms>3.3</avgbedrooms>
    <avgrentalprice>1194</avgrentalprice>
    <avgsalesprice>335792</avgsalesprice>
    <count>42</count>
  </dataset>
  <dataset>
    <postalcode>1150</postalcode>
    <avglivingarea>180</avglivingarea>
    <avgland>794</avgland>
    <avgbedrooms>3.3</avgbedrooms>
    <avgrentalprice>1797</avgrentalprice>
    <avgsalesprice>791995</avgsalesprice>
    <count>937</count>
  </dataset>
  <dataset>
    <postalcode>1800</postalcode>
    <avglivingarea>153</avglivingarea>
    <avgland>495</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>869</avgrentalprice>
    <avgsalesprice>289162</avgsalesprice>
    <count>251</count>
  </dataset>
  <dataset>
    <postalcode>1050</postalcode>
    <avglivingarea>211</avglivingarea>
    <avgland>235</avgland>
    <avgbedrooms>3.2</avgbedrooms>
    <avgrentalprice>2187</avgrentalprice>
    <avgsalesprice>872760</avgsalesprice>
    <count>1158</count>
  </dataset>
  <dataset>
    <postalcode>1082</postalcode>
    <avglivingarea>130</avglivingarea>
    <avgland>243</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice>906</avgrentalprice>
    <avgsalesprice>282519</avgsalesprice>
    <count>219</count>
  </dataset>
  <dataset>
    <postalcode>1170</postalcode>
    <avglivingarea>158</avglivingarea>
    <avgland>435</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>1741</avgrentalprice>
    <avgsalesprice>572625</avgsalesprice>
    <count>320</count>
  </dataset>
  <dataset>
    <postalcode>1950</postalcode>
    <avglivingarea>208</avglivingarea>
    <avgland>896</avgland>
    <avgbedrooms>3.7</avgbedrooms>
    <avgrentalprice>2105</avgrentalprice>
    <avgsalesprice>717560</avgsalesprice>
    <count>251</count>
  </dataset>
  <dataset>
    <postalcode>1090</postalcode>
    <avglivingarea>133</avglivingarea>
    <avgland>329</avgland>
    <avgbedrooms>2.8</avgbedrooms>
    <avgrentalprice>931</avgrentalprice>
    <avgsalesprice>289668</avgsalesprice>
    <count>452</count>
  </dataset>
  <dataset>
    <postalcode>1310</postalcode>
    <avglivingarea>210</avglivingarea>
    <avgland>1634</avgland>
    <avgbedrooms>3.7</avgbedrooms>
    <avgrentalprice>1559</avgrentalprice>
    <avgsalesprice>638518</avgsalesprice>
    <count>107</count>
  </dataset>
  <dataset>
    <postalcode>1700</postalcode>
    <avglivingarea>164</avglivingarea>
    <avgland>1158</avgland>
    <avgbedrooms>2.9</avgbedrooms>
    <avgrentalprice>867</avgrentalprice>
    <avgsalesprice>382277</avgsalesprice>
    <count>184</count>
  </dataset>
  <dataset>
    <postalcode>1850</postalcode>
    <avglivingarea>193</avglivingarea>
    <avgland>684</avgland>
    <avgbedrooms>3.2</avgbedrooms>
    <avgrentalprice>1088</avgrentalprice>
    <avgsalesprice>413689</avgsalesprice>
    <count>134</count>
  </dataset>
  <dataset>
    <postalcode>3500</postalcode>
    <avglivingarea>187</avglivingarea>
    <avgland>1862</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>908</avgrentalprice>
    <avgsalesprice>397448</avgsalesprice>
    <count>35</count>
  </dataset>
  <dataset>
    <postalcode>1120</postalcode>
    <avglivingarea>127</avglivingarea>
    <avgland>408</avgland>
    <avgbedrooms>2.6</avgbedrooms>
    <avgrentalprice>993</avgrentalprice>
    <avgsalesprice>258652</avgsalesprice>
    <count>132</count>
  </dataset>
  <dataset>
    <postalcode>1620</postalcode>
    <avglivingarea>152</avglivingarea>
    <avgland>323</avgland>
    <avgbedrooms>3</avgbedrooms>
    <avgrentalprice>990</avgrentalprice>
    <avgsalesprice>325667</avgsalesprice>
    <count>61</count>
  </dataset>
</main>
