<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (dataset*)>
  <!ELEMENT dataset (CATEGORY?,POSTAL_CODE?,TYPE?,COMMUNE?,BEDROOMS?,LIVING_AREA?,PRICE?)+>
  <!ELEMENT CATEGORY (#PCDATA)>
  <!ELEMENT POSTAL_CODE (#PCDATA)>
  <!ELEMENT TYPE (#PCDATA)>
  <!ELEMENT COMMUNE (#PCDATA)>
  <!ELEMENT BEDROOMS (#PCDATA)>
  <!ELEMENT LIVING_AREA (#PCDATA)>
  <!ELEMENT PRICE (#PCDATA)>
]>
<main>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>91</LIVING_AREA>
    <PRICE>395000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>91</LIVING_AREA>
    <PRICE>410000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>450000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>60</LIVING_AREA>
    <PRICE>225000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>103</LIVING_AREA>
    <PRICE>537000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>240</LIVING_AREA>
    <PRICE>895000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>365000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>122</LIVING_AREA>
    <PRICE>325000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>890000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>185</LIVING_AREA>
    <PRICE>475000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>230</LIVING_AREA>
    <PRICE>995000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>490000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>240</LIVING_AREA>
    <PRICE>895000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>97</LIVING_AREA>
    <PRICE>249000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>395000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>165</LIVING_AREA>
    <PRICE>450000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>181</LIVING_AREA>
    <PRICE>450000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>170</LIVING_AREA>
    <PRICE>645000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>172</LIVING_AREA>
    <PRICE>645000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>335000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>345000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>200</LIVING_AREA>
    <PRICE>495000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>92</LIVING_AREA>
    <PRICE>375000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>262</LIVING_AREA>
    <PRICE>789000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>300</LIVING_AREA>
    <PRICE>699500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>130</LIVING_AREA>
    <PRICE>375000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>255</LIVING_AREA>
    <PRICE>1200000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>230</LIVING_AREA>
    <PRICE>930000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>344000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>241</LIVING_AREA>
    <PRICE>895000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>280</LIVING_AREA>
    <PRICE>495000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>280</LIVING_AREA>
    <PRICE>590000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>144</LIVING_AREA>
    <PRICE>650000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>245</LIVING_AREA>
    <PRICE>789000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>225</LIVING_AREA>
    <PRICE>625000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>114</LIVING_AREA>
    <PRICE>330000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>94</LIVING_AREA>
    <PRICE>300000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>103</LIVING_AREA>
    <PRICE>537000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>241</LIVING_AREA>
    <PRICE>895000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>91</LIVING_AREA>
    <PRICE>395000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>91</LIVING_AREA>
    <PRICE>410000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>450000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>158</LIVING_AREA>
    <PRICE>499056</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>81</LIVING_AREA>
    <PRICE>201000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>75</LIVING_AREA>
    <PRICE>145000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>190000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>199000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>154</LIVING_AREA>
    <PRICE>349000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>360000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>225</LIVING_AREA>
    <PRICE>295000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>200</LIVING_AREA>
    <PRICE>279000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>149000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>107</LIVING_AREA>
    <PRICE>249000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>310000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>299000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>127</LIVING_AREA>
    <PRICE>260000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>155</LIVING_AREA>
    <PRICE>235000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>260</LIVING_AREA>
    <PRICE>429000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>192000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>179000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>225000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>195000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>91</LIVING_AREA>
    <PRICE>169000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>104</LIVING_AREA>
    <PRICE>185000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>80</LIVING_AREA>
    <PRICE>179000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>185</LIVING_AREA>
    <PRICE>370000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>400000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>200</LIVING_AREA>
    <PRICE>285000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>165000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>263</LIVING_AREA>
    <PRICE>395000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>89</LIVING_AREA>
    <PRICE>160000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>82</LIVING_AREA>
    <PRICE>187500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>130</LIVING_AREA>
    <PRICE>279000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>270</LIVING_AREA>
    <PRICE>450000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>209</LIVING_AREA>
    <PRICE>400000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>73</LIVING_AREA>
    <PRICE>150000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>149000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>94</LIVING_AREA>
    <PRICE>219000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>165</LIVING_AREA>
    <PRICE>225000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>200000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>83</LIVING_AREA>
    <PRICE>159000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>67</LIVING_AREA>
    <PRICE>125000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>210000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>210000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>220</LIVING_AREA>
    <PRICE>349000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>221000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>98</LIVING_AREA>
    <PRICE>189000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>279000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>175</LIVING_AREA>
    <PRICE>420000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>87</LIVING_AREA>
    <PRICE>135000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>220</LIVING_AREA>
    <PRICE>514000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>185000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>305000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>205000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>300</LIVING_AREA>
    <PRICE>390000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>225000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>75</LIVING_AREA>
    <PRICE>165000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>220</LIVING_AREA>
    <PRICE>349000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>126</LIVING_AREA>
    <PRICE>199000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>68</LIVING_AREA>
    <PRICE>165000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>75</LIVING_AREA>
    <PRICE>175000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>300000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>190</LIVING_AREA>
    <PRICE>285000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>179000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>107</LIVING_AREA>
    <PRICE>200000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>70</LIVING_AREA>
    <PRICE>142500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>199999</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>5</BEDROOMS>
    <LIVING_AREA>247</LIVING_AREA>
    <PRICE>375000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>199000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>70</LIVING_AREA>
    <PRICE>150000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>119000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>125</LIVING_AREA>
    <PRICE>249000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>131</LIVING_AREA>
    <PRICE>345000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>124900</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>177</LIVING_AREA>
    <PRICE>330000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>209999</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>200</LIVING_AREA>
    <PRICE>325000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>75</LIVING_AREA>
    <PRICE>154000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>
    <POSTAL_CODE>1020</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Laeken</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>200</LIVING_AREA>
    <PRICE>490000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Sales</CATEGORY>