<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (dataset*)>
  <!ELEMENT dataset (CATEGORY?,POSTAL_CODE?,TYPE?,COMMUNE?,BEDROOMS?,LIVING_AREA?,PRICE?)+>
  <!ELEMENT CATEGORY (#PCDATA)>
  <!ELEMENT POSTAL_CODE (#PCDATA)>
  <!ELEMENT TYPE (#PCDATA)>
  <!ELEMENT COMMUNE (#PCDATA)>
  <!ELEMENT BEDROOMS (#PCDATA)>
  <!ELEMENT LIVING_AREA (#PCDATA)>
  <!ELEMENT PRICE (#PCDATA)>
]>
<main>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>1100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>102</LIVING_AREA>
    <PRICE>2500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>76</LIVING_AREA>
    <PRICE>1050</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>115</LIVING_AREA>
    <PRICE>1750</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>70</LIVING_AREA>
    <PRICE>785</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>1150</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>1600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>165</LIVING_AREA>
    <PRICE>1900</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>290</LIVING_AREA>
    <PRICE>4500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>135</LIVING_AREA>
    <PRICE>2000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>165</LIVING_AREA>
    <PRICE>1900</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>240</LIVING_AREA>
    <PRICE>1750</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>270</LIVING_AREA>
    <PRICE>4400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>1950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>1650</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>1875</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>1600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>1600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>101</LIVING_AREA>
    <PRICE>1535</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>135</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>83</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>1650</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>211</LIVING_AREA>
    <PRICE>4500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>103</LIVING_AREA>
    <PRICE>2600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>1200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>115</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>106</LIVING_AREA>
    <PRICE>1000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>104</LIVING_AREA>
    <PRICE>1350</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>100</LIVING_AREA>
    <PRICE>1100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>2700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>1675</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>300</LIVING_AREA>
    <PRICE>6000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>82</LIVING_AREA>
    <PRICE>1250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>145</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>210</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>153</LIVING_AREA>
    <PRICE>1950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>270</LIVING_AREA>
    <PRICE>4400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>1975</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>290</LIVING_AREA>
    <PRICE>5500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>146</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>155</LIVING_AREA>
    <PRICE>4950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>2500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>1650</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>1250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>235</LIVING_AREA>
    <PRICE>2350</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>112</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>211</LIVING_AREA>
    <PRICE>4500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>220</LIVING_AREA>
    <PRICE>2250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>115</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>94</LIVING_AREA>
    <PRICE>2950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>149</LIVING_AREA>
    <PRICE>3200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>139</LIVING_AREA>
    <PRICE>2600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>1480</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>175</LIVING_AREA>
    <PRICE>3300</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>210</LIVING_AREA>
    <PRICE>4000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>1200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>2000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>88</LIVING_AREA>
    <PRICE>1300</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>95</LIVING_AREA>
    <PRICE>1150</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>103</LIVING_AREA>
    <PRICE>2600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>2700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>2500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>97</LIVING_AREA>
    <PRICE>850</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>155</LIVING_AREA>
    <PRICE>1800</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>170</LIVING_AREA>
    <PRICE>2400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>236</LIVING_AREA>
    <PRICE>2700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>156</LIVING_AREA>
    <PRICE>2500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>1700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>1350</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>112</LIVING_AREA>
    <PRICE>1400</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>67</LIVING_AREA>
    <PRICE>975</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>83</LIVING_AREA>
    <PRICE>1250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>980</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>106</LIVING_AREA>
    <PRICE>1600</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>1650</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>147</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>161</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>210</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>153</LIVING_AREA>
    <PRICE>1700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>1975</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>1950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>110</LIVING_AREA>
    <PRICE>2100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>275</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>83</LIVING_AREA>
    <PRICE>1250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>85</LIVING_AREA>
    <PRICE>850</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>119</LIVING_AREA>
    <PRICE>1975</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>99</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>70</LIVING_AREA>
    <PRICE>1250</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>125</LIVING_AREA>
    <PRICE>2100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>1500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>1475</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>3500</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>105</LIVING_AREA>
    <PRICE>950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>103</LIVING_AREA>
    <PRICE>1450</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>108</LIVING_AREA>
    <PRICE>1150</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>Apartment</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>1200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>2000</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>2750</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>126</LIVING_AREA>
    <PRICE>1200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>240</LIVING_AREA>
    <PRICE>1975</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>160</LIVING_AREA>
    <PRICE>1950</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>250</LIVING_AREA>
    <PRICE>3700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>70</LIVING_AREA>
    <PRICE>980</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>2100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>259</LIVING_AREA>
    <PRICE>2200</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>155</LIVING_AREA>
    <PRICE>1999</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>
    <LIVING_AREA>90</LIVING_AREA>
    <PRICE>1100</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>210</LIVING_AREA>
    <PRICE>2300</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>120</LIVING_AREA>
    <PRICE>1050</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>140</LIVING_AREA>
    <PRICE>1550</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>4</BEDROOMS>
    <LIVING_AREA>240</LIVING_AREA>
    <PRICE>2700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>6</BEDROOMS>
    <LIVING_AREA>270</LIVING_AREA>
    <PRICE>2700</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>3</BEDROOMS>
    <LIVING_AREA>150</LIVING_AREA>
    <PRICE>1800</PRICE>
  </dataset>
  <dataset>
    <CATEGORY>Rental</CATEGORY>
    <POSTAL_CODE>1000</POSTAL_CODE>
    <TYPE>House</TYPE>
    <COMMUNE>Ville de Bruxelles</COMMUNE>
    <BEDROOMS>2</BEDROOMS>