<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (dataset*)>
  <!ELEMENT dataset (POSTALCODE?,COMMUNE?,TYPE?,COUNT_RENTALS?,COUNT_SALES?,COUNT_TOTALS?)+>
  <!ELEMENT POSTALCODE (#PCDATA)>
  <!ELEMENT COMMUNE (#PCDATA)>
  <!ELEMENT TYPE (#PCDATA)>
  <!ELEMENT COUNT_RENTALS (#PCDATA)>
  <!ELEMENT COUNT_SALES (#PCDATA)>
  <!ELEMENT COUNT_TOTALS (#PCDATA)>
]>
<main>
  <dataset>
    <POSTALCODE>1000</POSTALCODE>
    <COMMUNE>BRUXELLES</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>102</COUNT_RENTALS>
    <COUNT_SALES>33</COUNT_SALES>
    <COUNT_TOTALS>135</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1000</POSTALCODE>
    <COMMUNE>BRUXELLES</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>91</COUNT_RENTALS>
    <COUNT_SALES>31</COUNT_SALES>
    <COUNT_TOTALS>122</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1020</POSTALCODE>
    <COMMUNE>Laeken</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>104</COUNT_RENTALS>
    <COUNT_SALES>165</COUNT_SALES>
    <COUNT_TOTALS>269</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1020</POSTALCODE>
    <COMMUNE>Laeken</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>31</COUNT_RENTALS>
    <COUNT_SALES>142</COUNT_SALES>
    <COUNT_TOTALS>173</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1030</POSTALCODE>
    <COMMUNE>SCHAERBEEK</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>139</COUNT_RENTALS>
    <COUNT_SALES>254</COUNT_SALES>
    <COUNT_TOTALS>393</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1030</POSTALCODE>
    <COMMUNE>SCHAERBEEK</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>376</COUNT_RENTALS>
    <COUNT_SALES>401</COUNT_SALES>
    <COUNT_TOTALS>777</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1040</POSTALCODE>
    <COMMUNE>ETTERBEEK</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>182</COUNT_RENTALS>
    <COUNT_SALES>125</COUNT_SALES>
    <COUNT_TOTALS>307</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1040</POSTALCODE>
    <COMMUNE>ETTERBEEK</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>432</COUNT_RENTALS>
    <COUNT_SALES>179</COUNT_SALES>
    <COUNT_TOTALS>611</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1050</POSTALCODE>
    <COMMUNE>IXELLES</COMMUNE>
    <TYPE>Building</TYPE>
    <COUNT_RENTALS>2</COUNT_RENTALS>
    <COUNT_SALES>8</COUNT_SALES>
    <COUNT_TOTALS>10</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1050</POSTALCODE>
    <COMMUNE>IXELLES</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>511</COUNT_RENTALS>
    <COUNT_SALES>344</COUNT_SALES>
    <COUNT_TOTALS>855</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1050</POSTALCODE>
    <COMMUNE>IXELLES</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>284</COUNT_RENTALS>
    <COUNT_SALES>310</COUNT_SALES>
    <COUNT_TOTALS>594</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1060</POSTALCODE>
    <COMMUNE>SAINT-GILLES</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>206</COUNT_RENTALS>
    <COUNT_SALES>123</COUNT_SALES>
    <COUNT_TOTALS>329</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1060</POSTALCODE>
    <COMMUNE>SAINT-GILLES</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>107</COUNT_RENTALS>
    <COUNT_SALES>103</COUNT_SALES>
    <COUNT_TOTALS>210</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1070</POSTALCODE>
    <COMMUNE>ANDERLECHT</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>150</COUNT_RENTALS>
    <COUNT_SALES>211</COUNT_SALES>
    <COUNT_TOTALS>361</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1070</POSTALCODE>
    <COMMUNE>ANDERLECHT</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>26</COUNT_RENTALS>
    <COUNT_SALES>257</COUNT_SALES>
    <COUNT_TOTALS>283</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1080</POSTALCODE>
    <COMMUNE>MOLENBEEK-SAINT-JEAN</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>30</COUNT_RENTALS>
    <COUNT_SALES>159</COUNT_SALES>
    <COUNT_TOTALS>189</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1080</POSTALCODE>
    <COMMUNE>MOLENBEEK-SAINT-JEAN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>124</COUNT_RENTALS>
    <COUNT_SALES>374</COUNT_SALES>
    <COUNT_TOTALS>498</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1081</POSTALCODE>
    <COMMUNE>KOEKELBERG</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>39</COUNT_RENTALS>
    <COUNT_SALES>123</COUNT_SALES>
    <COUNT_TOTALS>162</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1081</POSTALCODE>
    <COMMUNE>KOEKELBERG</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>9</COUNT_RENTALS>
    <COUNT_SALES>41</COUNT_SALES>
    <COUNT_TOTALS>50</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1082</POSTALCODE>
    <COMMUNE>BERCHEM-SAINTE-AGATHE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>47</COUNT_RENTALS>
    <COUNT_SALES>98</COUNT_SALES>
    <COUNT_TOTALS>145</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1082</POSTALCODE>
    <COMMUNE>BERCHEM-SAINTE-AGATHE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>12</COUNT_RENTALS>
    <COUNT_SALES>78</COUNT_SALES>
    <COUNT_TOTALS>90</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1083</POSTALCODE>
    <COMMUNE>GANSHOREN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>46</COUNT_RENTALS>
    <COUNT_SALES>111</COUNT_SALES>
    <COUNT_TOTALS>157</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1083</POSTALCODE>
    <COMMUNE>GANSHOREN</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>12</COUNT_RENTALS>
    <COUNT_SALES>54</COUNT_SALES>
    <COUNT_TOTALS>66</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1090</POSTALCODE>
    <COMMUNE>JETTE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>111</COUNT_RENTALS>
    <COUNT_SALES>199</COUNT_SALES>
    <COUNT_TOTALS>310</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1090</POSTALCODE>
    <COMMUNE>JETTE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>22</COUNT_RENTALS>
    <COUNT_SALES>160</COUNT_SALES>
    <COUNT_TOTALS>182</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1120</POSTALCODE>
    <COMMUNE>Neder-Over-Heembeek</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>9</COUNT_RENTALS>
    <COUNT_SALES>42</COUNT_SALES>
    <COUNT_TOTALS>51</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1120</POSTALCODE>
    <COMMUNE>Neder-Over-Heembeek</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>27</COUNT_RENTALS>
    <COUNT_SALES>59</COUNT_SALES>
    <COUNT_TOTALS>86</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1130</POSTALCODE>
    <COMMUNE>Haren</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>3</COUNT_RENTALS>
    <COUNT_SALES>5</COUNT_SALES>
    <COUNT_TOTALS>8</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1130</POSTALCODE>
    <COMMUNE>Haren</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>3</COUNT_RENTALS>
    <COUNT_SALES>33</COUNT_SALES>
    <COUNT_TOTALS>36</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1140</POSTALCODE>
    <COMMUNE>EVERE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>48</COUNT_RENTALS>
    <COUNT_SALES>94</COUNT_SALES>
    <COUNT_TOTALS>142</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1140</POSTALCODE>
    <COMMUNE>EVERE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>180</COUNT_RENTALS>
    <COUNT_SALES>156</COUNT_SALES>
    <COUNT_TOTALS>336</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1150</POSTALCODE>
    <COMMUNE>WOLUWE-SAINT-PIERRE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>331</COUNT_RENTALS>
    <COUNT_SALES>236</COUNT_SALES>
    <COUNT_TOTALS>567</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1150</POSTALCODE>
    <COMMUNE>WOLUWE-SAINT-PIERRE</COMMUNE>
    <TYPE>Building</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>2</COUNT_SALES>
    <COUNT_TOTALS>3</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1150</POSTALCODE>
    <COMMUNE>WOLUWE-SAINT-PIERRE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>546</COUNT_RENTALS>
    <COUNT_SALES>147</COUNT_SALES>
    <COUNT_TOTALS>693</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1160</POSTALCODE>
    <COMMUNE>AUDERGHEM</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>239</COUNT_RENTALS>
    <COUNT_SALES>108</COUNT_SALES>
    <COUNT_TOTALS>347</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1160</POSTALCODE>
    <COMMUNE>AUDERGHEM</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>148</COUNT_RENTALS>
    <COUNT_SALES>131</COUNT_SALES>
    <COUNT_TOTALS>279</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1170</POSTALCODE>
    <COMMUNE>WATERMAEL-BOITSFORT</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>120</COUNT_RENTALS>
    <COUNT_SALES>89</COUNT_SALES>
    <COUNT_TOTALS>209</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1170</POSTALCODE>
    <COMMUNE>WATERMAEL-BOITSFORT</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>90</COUNT_RENTALS>
    <COUNT_SALES>77</COUNT_SALES>
    <COUNT_TOTALS>167</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1180</POSTALCODE>
    <COMMUNE>UCCLE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>501</COUNT_RENTALS>
    <COUNT_SALES>279</COUNT_SALES>
    <COUNT_TOTALS>780</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1180</POSTALCODE>
    <COMMUNE>UCCLE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>547</COUNT_RENTALS>
    <COUNT_SALES>603</COUNT_SALES>
    <COUNT_TOTALS>1150</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1190</POSTALCODE>
    <COMMUNE>FOREST</COMMUNE>
    <TYPE>Building</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>3</COUNT_SALES>
    <COUNT_TOTALS>4</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1190</POSTALCODE>
    <COMMUNE>FOREST</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>197</COUNT_RENTALS>
    <COUNT_SALES>243</COUNT_SALES>
    <COUNT_TOTALS>440</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1190</POSTALCODE>
    <COMMUNE>FOREST</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>77</COUNT_RENTALS>
    <COUNT_SALES>173</COUNT_SALES>
    <COUNT_TOTALS>250</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1200</POSTALCODE>
    <COMMUNE>WOLUWE-SAINT-LAMBERT</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>515</COUNT_RENTALS>
    <COUNT_SALES>182</COUNT_SALES>
    <COUNT_TOTALS>697</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1200</POSTALCODE>
    <COMMUNE>WOLUWE-SAINT-LAMBERT</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>227</COUNT_RENTALS>
    <COUNT_SALES>140</COUNT_SALES>
    <COUNT_TOTALS>367</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1210</POSTALCODE>
    <COMMUNE>SAINT-JOSSE-TEN-NOODE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>20</COUNT_RENTALS>
    <COUNT_SALES>28</COUNT_SALES>
    <COUNT_TOTALS>48</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1210</POSTALCODE>
    <COMMUNE>SAINT-JOSSE-TEN-NOODE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>51</COUNT_RENTALS>
    <COUNT_SALES>64</COUNT_SALES>
    <COUNT_TOTALS>115</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1310</POSTALCODE>
    <COMMUNE>LA HULPE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>48</COUNT_RENTALS>
    <COUNT_SALES>50</COUNT_SALES>
    <COUNT_TOTALS>98</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1310</POSTALCODE>
    <COMMUNE>LA HULPE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>9</COUNT_RENTALS>
    <COUNT_SALES>3</COUNT_SALES>
    <COUNT_TOTALS>12</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1370</POSTALCODE>
    <COMMUNE>Dongelberg</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>2</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1410</POSTALCODE>
    <COMMUNE>WATERLOO</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>3</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>4</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1620</POSTALCODE>
    <COMMUNE>DROGENBOS</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>6</COUNT_RENTALS>
    <COUNT_SALES>35</COUNT_SALES>
    <COUNT_TOTALS>41</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1620</POSTALCODE>
    <COMMUNE>DROGENBOS</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>14</COUNT_RENTALS>
    <COUNT_SALES>11</COUNT_SALES>
    <COUNT_TOTALS>25</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1700</POSTALCODE>
    <COMMUNE>DILBEEK</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>40</COUNT_RENTALS>
    <COUNT_SALES>27</COUNT_SALES>
    <COUNT_TOTALS>67</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1700</POSTALCODE>
    <COMMUNE>DILBEEK</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>29</COUNT_RENTALS>
    <COUNT_SALES>99</COUNT_SALES>
    <COUNT_TOTALS>128</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1780</POSTALCODE>
    <COMMUNE>WEMMEL</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>49</COUNT_RENTALS>
    <COUNT_SALES>45</COUNT_SALES>
    <COUNT_TOTALS>94</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1780</POSTALCODE>
    <COMMUNE>WEMMEL</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>32</COUNT_RENTALS>
    <COUNT_SALES>105</COUNT_SALES>
    <COUNT_TOTALS>137</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1800</POSTALCODE>
    <COMMUNE>Vilvoorde</COMMUNE>
    <TYPE>Building</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>10</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1800</POSTALCODE>
    <COMMUNE>Vilvoorde</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>26</COUNT_RENTALS>
    <COUNT_SALES>59</COUNT_SALES>
    <COUNT_TOTALS>85</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1800</POSTALCODE>
    <COMMUNE>Vilvoorde</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>14</COUNT_RENTALS>
    <COUNT_SALES>146</COUNT_SALES>
    <COUNT_TOTALS>160</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1850</POSTALCODE>
    <COMMUNE>GRIMBERGEN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>19</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>28</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1850</POSTALCODE>
    <COMMUNE>GRIMBERGEN</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>24</COUNT_RENTALS>
    <COUNT_SALES>89</COUNT_SALES>
    <COUNT_TOTALS>113</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1853</POSTALCODE>
    <COMMUNE>Strombeek-Bever</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>7</COUNT_RENTALS>
    <COUNT_SALES>66</COUNT_SALES>
    <COUNT_TOTALS>73</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1853</POSTALCODE>
    <COMMUNE>Strombeek-Bever</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>37</COUNT_RENTALS>
    <COUNT_SALES>39</COUNT_SALES>
    <COUNT_TOTALS>76</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1930</POSTALCODE>
    <COMMUNE>Nossegem</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>38</COUNT_RENTALS>
    <COUNT_SALES>34</COUNT_SALES>
    <COUNT_TOTALS>72</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1930</POSTALCODE>
    <COMMUNE>Nossegem</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>37</COUNT_RENTALS>
    <COUNT_SALES>74</COUNT_SALES>
    <COUNT_TOTALS>111</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1932</POSTALCODE>
    <COMMUNE>Sint-Stevens-Woluwe</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>28</COUNT_RENTALS>
    <COUNT_SALES>14</COUNT_SALES>
    <COUNT_TOTALS>42</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1932</POSTALCODE>
    <COMMUNE>Sint-Stevens-Woluwe</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>18</COUNT_RENTALS>
    <COUNT_SALES>28</COUNT_SALES>
    <COUNT_TOTALS>46</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1950</POSTALCODE>
    <COMMUNE>KRAAINEM</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>127</COUNT_RENTALS>
    <COUNT_SALES>116</COUNT_SALES>
    <COUNT_TOTALS>243</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1950</POSTALCODE>
    <COMMUNE>KRAAINEM</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>37</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>46</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1970</POSTALCODE>
    <COMMUNE>WEZEMBEEK-OPPEM</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>107</COUNT_RENTALS>
    <COUNT_SALES>120</COUNT_SALES>
    <COUNT_TOTALS>227</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>1970</POSTALCODE>
    <COMMUNE>WEZEMBEEK-OPPEM</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>25</COUNT_RENTALS>
    <COUNT_SALES>19</COUNT_SALES>
    <COUNT_TOTALS>44</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2000</POSTALCODE>
    <COMMUNE>ANTWERPEN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>6</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>15</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2000</POSTALCODE>
    <COMMUNE>ANTWERPEN</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>7</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>8</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2100</POSTALCODE>
    <COMMUNE>Deurne</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>10</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2140</POSTALCODE>
    <COMMUNE>Borgerhout</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>2</COUNT_RENTALS>
    <COUNT_SALES>4</COUNT_SALES>
    <COUNT_TOTALS>6</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2170</POSTALCODE>
    <COMMUNE>Merksem</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>16</COUNT_SALES>
    <COUNT_TOTALS>17</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2570</POSTALCODE>
    <COMMUNE>DUFFEL</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>2</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2600</POSTALCODE>
    <COMMUNE>Berchem</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>2</COUNT_RENTALS>
    <COUNT_SALES>8</COUNT_SALES>
    <COUNT_TOTALS>10</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2610</POSTALCODE>
    <COMMUNE>Wilrijk</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>7</COUNT_SALES>
    <COUNT_TOTALS>8</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2660</POSTALCODE>
    <COMMUNE>Hoboken</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>18</COUNT_SALES>
    <COUNT_TOTALS>19</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2900</POSTALCODE>
    <COMMUNE>SCHOTEN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>4</COUNT_RENTALS>
    <COUNT_SALES>2</COUNT_SALES>
    <COUNT_TOTALS>6</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2930</POSTALCODE>
    <COMMUNE>BRASSCHAAT</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>2</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2930</POSTALCODE>
    <COMMUNE>BRASSCHAAT</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>5</COUNT_SALES>
    <COUNT_TOTALS>6</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2940</POSTALCODE>
    <COMMUNE>Hoevenen</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>2</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>2970</POSTALCODE>
    <COMMUNE>&#39;S Gravenwezel</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>1</COUNT_RENTALS>
    <COUNT_SALES>1</COUNT_SALES>
    <COUNT_TOTALS>2</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3000</POSTALCODE>
    <COMMUNE>LEUVEN</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>4</COUNT_RENTALS>
    <COUNT_SALES>2</COUNT_SALES>
    <COUNT_TOTALS>6</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3080</POSTALCODE>
    <COMMUNE>Duisburg</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>31</COUNT_RENTALS>
    <COUNT_SALES>17</COUNT_SALES>
    <COUNT_TOTALS>48</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3080</POSTALCODE>
    <COMMUNE>Duisburg</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>258</COUNT_RENTALS>
    <COUNT_SALES>160</COUNT_SALES>
    <COUNT_TOTALS>418</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3090</POSTALCODE>
    <COMMUNE>OVERIJSE</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>31</COUNT_RENTALS>
    <COUNT_SALES>19</COUNT_SALES>
    <COUNT_TOTALS>50</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3090</POSTALCODE>
    <COMMUNE>OVERIJSE</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>171</COUNT_RENTALS>
    <COUNT_SALES>160</COUNT_SALES>
    <COUNT_TOTALS>331</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3300</POSTALCODE>
    <COMMUNE>Bost</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>4</COUNT_RENTALS>
    <COUNT_SALES>2</COUNT_SALES>
    <COUNT_TOTALS>6</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3300</POSTALCODE>
    <COMMUNE>Bost</COMMUNE>
    <TYPE>House</TYPE>
    <COUNT_RENTALS>3</COUNT_RENTALS>
    <COUNT_SALES>17</COUNT_SALES>
    <COUNT_TOTALS>20</COUNT_TOTALS>
  </dataset>
  <dataset>
    <POSTALCODE>3500</POSTALCODE>
    <COMMUNE>HASSELT</COMMUNE>
    <TYPE>Apartment</TYPE>
    <COUNT_RENTALS>6</COUNT_RENTALS>
    <COUNT_SALES>9</COUNT_SALES>
    <COUNT_TOTALS>15</COUNT_TOTALS>
  </dataset>
</main>
